openapi: '3.0'
info:
  title: VDJServer API
  version: '2.0.0'
  contact:
    name: VDJServer
    url: 'https://vdjserver.org/'
    email: vdjserver@utsouthwestern.edu
  description: >
    API service for the VDJServer analysis portal.

servers:
  - url: https://vdjserver.org/api/v2
    description: Development server
    variables:
      basePath:
        default: /api/v2

paths:
  /:
    get:
      description: |
        Service heartbeat.
      operationId: getStatus
      responses:
        '200':
          description: |
            Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string

